version: "3.2"

services:
    app:
      build:        
        context: .
        dockerfile: Dockerfile        
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/app:${CIRCLE_SHA1}
      ports:
        - "3000:3000"
      environment:
        AWS_ACCOUNT_ID: 123        

    load-balancer:
      build:
        context: .
        dockerfile: ./Dockerfile.nginx
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/load-balancer:${CIRCLE_SHA1}
      ports:
        - "80:80"
      links:
        - "app"