version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.11.76
      - run: 
          name: Build application docker image
          command: |
            docker build -t app .
      - deploy:
          name: Push application Docker image
          command: | 
            
            DOCKER_IMAGE='app'
            CLUSTER='app'
            FAMILY='app'
            DOCKER_IMAGE='app'
            TASK='app'
            SERVICE='app-service'

            # Login to AWS
            aws configure set region $AWS_REGION
            $(aws ecr get-login)

            # Tag and push docker image
            docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1

            # Create task for docker deploy
            task_template='[
                {
                  "name": "%s",
                  "image": "%s.dkr.ecr.eu-west-1.amazonaws.com/%s:%s",
                  "essential": true,
                  "memoryReservation": 1000,
                  "portMappings": [
                    {
                      "containerPort": 3000,
                      "hostPort": 80
                    }
                  ],
                  "environment" : [
                      { "name" : "NODE_ENV", "value" : "production" }
                  ]
                }
            ]'
            echo "$task_template"
            
            task_def=$(printf "$task_template" $TASK $AWS_ACCOUNT_ID $TASK $CIRCLE_SHA1)

            echo "$task_def"
            
            # Register task definition
            json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")
            
            # Grab revision # using regular bash and grep
            revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')
            
            
            # Deploy revision
            aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
            return 0
  test:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run: 
          name: Install app and test
          command: |
            apt-get install npm
            npm install && npm test
            
# Workflow 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test